name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify commit exists in origin/main
        run: git branch --remote --contains | grep origin/main

      - name: Extract release notes
        run: |
          git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: (\d+.\d+.\d)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}

      - name: Test
        run: dotnet test --configuration Release /p:Version=${{ env.VERSION }} --no-build

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ env.VERSION }} --no-build --output .

      - name: Push

        run: dotnet nuget push LightMemoryCache.${{ env.VERSION }}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
